"""
Admin audit report — a PDF summary of verified donations over a date range,
broken down by campaign, with a full donation-level ledger.

Reuses the same Bengali-shaping approach as accounts/receipt.py (see that
file for why reportlab needs help with Bengali) rather than duplicating it.

IMPORTANT: reportlab's built-in fonts (Helvetica etc.) have NO Bengali
glyphs, so any Bengali text must go through _cell()/_render_unicode_text_image()
below — never through a plain Paragraph(bengali_text, ...) call, or it
silently renders as blank boxes instead of raising an error.
"""
from io import BytesIO, StringIO
from decimal import Decimal

from django.utils import timezone

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER

from accounts.receipt import _cell, _render_unicode_text_image

GREEN = colors.HexColor('#15803d')
LGREEN = colors.HexColor('#dcfce7')
GRAY = colors.HexColor('#6b7280')
DARK = colors.HexColor('#111827')
WHITE_RGB = (255, 255, 255)
DARK_RGB = (17, 24, 39)
GRAY_RGB = (107, 114, 128)
GREEN_RGB = (21, 128, 61)
LIGHT_GRID = colors.HexColor('#e5e7eb')
ROW_ALT = colors.HexColor('#f9fafb')


def generate_audit_report_pdf(donations, date_from, date_to, campaign_filter_label, generated_by):
    """
    donations: an already-filtered, already-verified Donation queryset
        (select_related('campaign') recommended), for the report period.
    date_from / date_to: date objects, or None for "no bound".
    campaign_filter_label: human-readable string describing which
        campaign(s) this report covers (e.g. "সব ক্যাম্পেইন" or a specific name).
    generated_by: display name/username of the staff user who generated this.
    Returns a BytesIO containing the PDF.
    """
    donations = list(donations.order_by('campaign__title', 'created_at'))

    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        rightMargin=16 * mm, leftMargin=16 * mm,
        topMargin=16 * mm, bottomMargin=16 * mm,
    )
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'Title', parent=styles['Normal'], fontSize=20, leading=24,
        fontName='Helvetica-Bold', textColor=GREEN, alignment=TA_CENTER, spaceAfter=2,
    )
    subtitle_style = ParagraphStyle(
        'Sub', parent=styles['Normal'], fontSize=9.5, leading=13,
        fontName='Helvetica', textColor=GRAY, alignment=TA_CENTER,
    )
    section_style = ParagraphStyle(
        'Section', parent=styles['Normal'], fontSize=12, leading=15,
        fontName='Helvetica-Bold', textColor=DARK, spaceBefore=14, spaceAfter=6,
    )
    label_style = ParagraphStyle(
        'Label', parent=styles['Normal'], fontSize=8.5, leading=11,
        fontName='Helvetica', textColor=GRAY,
    )
    value_style = ParagraphStyle(
        'Value', parent=styles['Normal'], fontSize=9, leading=12,
        fontName='Helvetica-Bold', textColor=DARK,
    )
    th_style = ParagraphStyle(
        'TH', parent=styles['Normal'], fontSize=8.5, leading=11,
        fontName='Helvetica-Bold', textColor=colors.white,
    )
    td_style = ParagraphStyle(
        'TD', parent=styles['Normal'], fontSize=8.5, leading=11,
        fontName='Helvetica', textColor=DARK,
    )

    def bn(text, style, color_rgb=DARK_RGB):
        """Shortcut: rasterize Bengali/mixed text correctly for a table cell."""
        return _cell(text, style, color_rgb=color_rgb)

    story = []

    # ── HEADER ──
    story.append(bn("Sahay.bd — অডিট প্রতিবেদন", title_style, GREEN_RGB))
    story.append(Paragraph("Donation Audit Report | sohay.pythonanywhere.com", subtitle_style))
    story.append(HRFlowable(width='100%', thickness=2, color=GREEN, spaceBefore=8, spaceAfter=10))

    # ── REPORT META (period, filter, generated by/when) ──
    period_str = (
        f"{date_from.strftime('%d %b %Y') if date_from else 'শুরু থেকে'}"
        f" - "
        f"{date_to.strftime('%d %b %Y') if date_to else 'বর্তমান'}"
    )
    meta_rows = [
        [bn("রিপোর্ট সময়কাল", label_style, GRAY_RGB), bn(period_str, value_style),
         bn("তৈরির তারিখ", label_style, GRAY_RGB), Paragraph(timezone.now().strftime('%d %b %Y, %I:%M %p'), value_style)],
        [bn("ক্যাম্পেইন", label_style, GRAY_RGB), bn(campaign_filter_label, value_style),
         bn("তৈরি করেছেন", label_style, GRAY_RGB), bn(generated_by, value_style)],
    ]
    meta_table = Table(meta_rows, colWidths=['20%', '30%', '20%', '30%'])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), LGREEN),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('LEFTPADDING', (0, 0), (-1, -1), 9),
        ('RIGHTPADDING', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ROUNDEDCORNERS', [4, 4, 4, 4]),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    # ── SUMMARY ──
    total_amount = sum((d.amount for d in donations), Decimal('0'))
    total_count = len(donations)

    summary_rows = [
        [bn("মোট ভেরিফায়েড ডোনেশন", label_style, GRAY_RGB), Paragraph(str(total_count), value_style),
         bn("মোট সংগৃহীত অর্থ", label_style, GRAY_RGB), bn(f"৳{total_amount:,.2f}", value_style, GREEN_RGB)],
    ]
    summary_table = Table(summary_rows, colWidths=['30%', '20%', '30%', '20%'])
    summary_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, LIGHT_GRID),
        ('BACKGROUND', (0, 0), (0, -1), ROW_ALT),
        ('BACKGROUND', (2, 0), (2, -1), ROW_ALT),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('LEFTPADDING', (0, 0), (-1, -1), 9),
        ('RIGHTPADDING', (0, 0), (-1, -1), 9),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(summary_table)

    # ── PER-CAMPAIGN BREAKDOWN ──
    story.append(bn("ক্যাম্পেইন অনুযায়ী বিভাজন", section_style, DARK_RGB))

    breakdown = {}
    for d in donations:
        key = d.campaign.title
        if key not in breakdown:
            breakdown[key] = {'count': 0, 'total': Decimal('0')}
        breakdown[key]['count'] += 1
        breakdown[key]['total'] += d.amount
    sorted_breakdown = sorted(breakdown.items(), key=lambda kv: kv[1]['total'], reverse=True)

    header_row = [
        bn("ক্যাম্পেইন", th_style, WHITE_RGB),
        bn("ডোনেশন সংখ্যা", th_style, WHITE_RGB),
        bn("মোট অর্থ (৳)", th_style, WHITE_RGB),
    ]
    campaign_rows = [header_row]
    for title, agg in sorted_breakdown:
        campaign_rows.append([
            bn(title, td_style),
            Paragraph(str(agg['count']), td_style),
            bn(f"৳{agg['total']:,.2f}", td_style),
        ])
    if not sorted_breakdown:
        campaign_rows.append([bn("এই সময়সীমায় কোনো ভেরিফায়েড ডোনেশন পাওয়া যায়নি।", td_style), '', ''])

    campaign_table = Table(campaign_rows, colWidths=['55%', '20%', '25%'], repeatRows=1)
    campaign_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), GREEN),
        ('GRID', (0, 0), (-1, -1), 0.5, LIGHT_GRID),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (-1, -1), 'RIGHT'),  # counts + amounts, right-aligned
    ]))
    story.append(campaign_table)

    # ── DETAILED LEDGER ──
    story.append(bn("বিস্তারিত ডোনেশন লেজার", section_style, DARK_RGB))

    ledger_header = [
        bn("তারিখ", th_style, WHITE_RGB),
        bn("ক্যাম্পেইন", th_style, WHITE_RGB),
        bn("দাতা", th_style, WHITE_RGB),
        bn("মাধ্যম", th_style, WHITE_RGB),
        bn("রেফারেন্স", th_style, WHITE_RGB),
        bn("অর্থ (৳)", th_style, WHITE_RGB),
    ]
    ledger_rows = [ledger_header]
    for d in donations:
        ledger_rows.append([
            Paragraph(d.created_at.strftime('%d-%m-%Y'), td_style),
            bn(d.campaign.title, td_style),
            bn(d.display_name, td_style),
            bn(d.get_payment_method_display(), td_style),
            Paragraph(d.payment_reference or '-', td_style),
            bn(f"৳{d.amount:,.2f}", td_style),
        ])
    if len(ledger_rows) == 1:
        ledger_rows.append([Paragraph('-', td_style), '', '', '', '', ''])

    ledger_table = Table(
        ledger_rows,
        colWidths=['13%', '27%', '20%', '13%', '14%', '13%'],
        repeatRows=1,
    )
    ledger_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), GREEN),
        ('GRID', (0, 0), (-1, -1), 0.4, LIGHT_GRID),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, ROW_ALT]),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LEFTPADDING', (0, 0), (-1, -1), 6),
        ('RIGHTPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (5, 0), (5, -1), 'RIGHT'),  # amount column
    ]))
    story.append(ledger_table)

    # ── FOOTER NOTE ──
    story.append(Spacer(1, 14))
    story.append(HRFlowable(width='100%', thickness=1, color=LIGHT_GRID, spaceAfter=8))
    footer_line_1 = "এই রিপোর্টে শুধুমাত্র ভেরিফায়েড (is_verified=True) ডোনেশন অন্তর্ভুক্ত করা হয়েছে।"
    footer_line_2 = "যাচাই-বাকি ডোনেশন এই হিসাবের অংশ নয়। এটি একটি কম্পিউটার-জেনারেটেড প্রতিবেদন।"
    for line in (footer_line_1, footer_line_2):
        img = _render_unicode_text_image(line, font_size=7.5, color_rgb=GRAY_RGB, max_width_pt=500)
        img.hAlign = 'CENTER'
        story.append(img)

    doc.build(story)
    buf.seek(0)
    return buf


def generate_audit_report_csv(donations, date_from, date_to):
    """
    Same underlying data as the PDF report, but as plain CSV — for admins
    who want to open it in Excel/Sheets themselves rather than read a PDF.
    Only ever called with an already is_verified=True filtered queryset,
    same as the PDF path.
    """
    import csv

    donations = list(donations.order_by('campaign__title', 'created_at'))

    buf = StringIO()
    writer = csv.writer(buf)

    writer.writerow(['Sahay.bd Audit Report'])
    writer.writerow(['Period', f"{date_from or 'start'} to {date_to or 'today'}"])
    writer.writerow(['Generated', timezone.now().strftime('%Y-%m-%d %H:%M')])
    writer.writerow([])

    writer.writerow(['Date', 'Campaign', 'Donor', 'Payment Method', 'Reference', 'Amount (BDT)'])
    total = Decimal('0')
    for d in donations:
        writer.writerow([
            d.created_at.strftime('%Y-%m-%d'),
            d.campaign.title,
            d.display_name,
            d.get_payment_method_display(),
            d.payment_reference or '',
            str(d.amount),
        ])
        total += d.amount

    writer.writerow([])
    writer.writerow(['', '', '', '', 'TOTAL', str(total)])
    writer.writerow(['', '', '', '', 'COUNT', str(len(donations))])

    buf.seek(0)
    return buf
