# Generated by Django 6.0.6 on 2026-07-15 10:44

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0005_volunteer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='নাম')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'ব্লগ ক্যাটাগরি',
                'verbose_name_plural': 'ব্লগ ক্যাটাগরিসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='নাম')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'ট্যাগ',
                'verbose_name_plural': 'ট্যাগসমূহ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='শিরোনাম (বাংলা)')),
                ('title_en', models.CharField(blank=True, help_text='ঐচ্ছিক — English ভার্সনে দেখাতে চাইলে দিন', max_length=255, verbose_name='Title (English)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('excerpt', models.CharField(help_text='লিস্টিং পেজ ও সার্চ ইঞ্জিনে (SEO) এই লেখাটি দেখাবে', max_length=300, verbose_name='সংক্ষিপ্ত বিবরণ')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='বিস্তারিত লেখা')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='কভার ছবি')),
                ('author_name', models.CharField(default='সহায়.bd টিম', max_length=100, verbose_name='লেখক')),
                ('status', models.CharField(choices=[('draft', 'খসড়া'), ('published', 'প্রকাশিত'), ('scheduled', 'নির্ধারিত সময়ে প্রকাশ হবে')], default='draft', max_length=20, verbose_name='অবস্থা')),
                ('published_at', models.DateTimeField(blank=True, help_text='ফাঁকা রাখলে, "প্রকাশিত" করে সেভ করার সময় এখনকার সময় বসে যাবে। ভবিষ্যতের কোনো সময় দিলে, সেই সময়ের আগে পোস্টটি সাইটে দেখাবে না।', null=True, verbose_name='প্রকাশের সময়')),
                ('meta_title', models.CharField(blank=True, help_text='ফাঁকা রাখলে পোস্টের শিরোনামই ব্যবহার হবে', max_length=255, verbose_name='Meta Title')),
                ('meta_description', models.CharField(blank=True, help_text='ফাঁকা রাখলে সংক্ষিপ্ত বিবরণ ব্যবহার হবে', max_length=300, verbose_name='Meta Description')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='ক্যাটাগরি')),
                ('related_campaign', models.ForeignKey(blank=True, help_text='এই পোস্টের Donate বাটনগুলো এই ক্যাম্পেইনের দিকে নির্দেশ করবে (না দিলে, সবচেয়ে জরুরি/ফিচার্ড ক্যাম্পেইন দেখাবে)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='campaigns.campaign', verbose_name='সম্পর্কিত ক্যাম্পেইন')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.blogtag', verbose_name='ট্যাগসমূহ')),
            ],
            options={
                'verbose_name': 'ব্লগ পোস্ট',
                'verbose_name_plural': 'ব্লগ পোস্টসমূহ',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
