# Generated by Django 6.0.6 on 2026-07-16 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000, verbose_name='মন্তব্য')),
                ('is_approved', models.BooleanField(default=True, help_text='আপত্তিকর বা স্প্যাম মন্তব্য লুকাতে আনচেক করুন', verbose_name='দৃশ্যমান')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'মন্তব্য',
                'verbose_name_plural': 'মন্তব্যসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
