# Generated by Django 6.0.6 on 2026-07-17 02:10

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='স্বয়ংক্রিয় অনুবাদ — admin action দিয়ে ভরা যায়, পরে ঠিক করে নেওয়া যায়', verbose_name='বিস্তারিত লেখা (English)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.CharField(blank=True, help_text='স্বয়ংক্রিয় অনুবাদ — admin action দিয়ে ভরা যায়', max_length=300, verbose_name='Excerpt (English)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, help_text='ঐচ্ছিক — English ভার্সনে দেখাতে চাইলে দিন, অথবা নিচের "Translate to English" action ব্যবহার করুন', max_length=255, verbose_name='Title (English)'),
        ),
    ]
