# Generated by Django 6.0.6 on 2026-06-14 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('donor_name', models.CharField(blank=True, default='', max_length=200)),
                ('donor_phone', models.CharField(blank=True, max_length=20)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('bkash', 'বিকাশ'), ('nagad', 'নগদ'), ('rocket', 'রকেট'), ('bank', 'ব্যাংক'), ('cash', 'নগদ অর্থ')], default='bkash', max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction/Reference নম্বর', max_length=100)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
