# Generated by Django 6.0.6 on 2026-06-17 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, help_text='প্রতিবার কত টাকা দিতে চান', max_digits=10)),
                ('frequency', models.CharField(choices=[('monthly', 'মাসিক'), ('weekly', 'সাপ্তাহিক')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_reminded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, help_text='খালি রাখলে general reminder (নির্দিষ্ট কোনো ক্যাম্পেইন না)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'রিকারিং রিমাইন্ডার',
                'verbose_name_plural': 'রিকারিং রিমাইন্ডার',
                'ordering': ['-created_at'],
            },
        ),
    ]
