# Generated by Django 6.0.6 on 2026-06-18 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='অজ্ঞাত', max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=True, help_text='অনুপযুক্ত মন্তব্য হলে আনচেক করুন')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'মন্তব্য',
                'verbose_name_plural': 'মন্তব্যসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
