# Generated by Django 6.0.6 on 2026-06-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='description_en',
            field=models.TextField(blank=True, help_text='স্বয়ংক্রিয় অনুবাদ'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='short_description_en',
            field=models.CharField(blank=True, help_text='স্বয়ংক্রিয় অনুবাদ', max_length=350),
        ),
        migrations.AddField(
            model_name='campaign',
            name='title_en',
            field=models.CharField(blank=True, help_text="স্বয়ংক্রিয় অনুবাদ — admin-এ 'Translate to English' action ব্যবহার করুন", max_length=255),
        ),
    ]
