# Generated by Django 6.0.6 on 2026-06-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='পুরো নাম')),
                ('phone', models.CharField(max_length=20, verbose_name='মোবাইল নম্বর')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ইমেইল (ঐচ্ছিক)')),
                ('profession', models.CharField(max_length=200, verbose_name='পেশা')),
                ('address', models.TextField(verbose_name='বর্তমান ঠিকানা')),
                ('nid', models.CharField(max_length=30, verbose_name='NID / জাতীয় পরিচয়পত্র নম্বর')),
                ('why_volunteer', models.TextField(blank=True, help_text='সংক্ষেপে লিখুন (ঐচ্ছিক)', verbose_name='কেন ভলান্টিয়ার হতে চান?')),
                ('status', models.CharField(choices=[('pending', 'বিচারাধীন'), ('approved', 'অনুমোদিত'), ('rejected', 'প্রত্যাখ্যাত')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, verbose_name='Admin নোট')),
            ],
            options={
                'verbose_name': 'ভলান্টিয়ার',
                'verbose_name_plural': 'ভলান্টিয়ারসমূহ',
                'ordering': ['-created_at'],
            },
        ),
    ]
