# Generated by Django 6.0.7 on 2026-07-24 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_volunteer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='অনুমোদনের তারিখ'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='volunteers/', verbose_name='ছবি (ID card ও verify পেজে দেখাবে)'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_profile', to=settings.AUTH_USER_MODEL, verbose_name='অ্যাকাউন্ট'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='volunteer_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='ভলান্টিয়ার আইডি'),
        ),
    ]
