# Generated by Django 6.0.7 on 2026-08-02 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_volunteer_approved_at_volunteer_photo_volunteer_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, help_text='যেই যাচাইকৃত দাতা অ্যাকাউন্ট থেকে মন্তব্যটি করা হয়েছে', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campaign_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
